"""UI主题定义 - 黑色/白色风格 (增强版)"""

THEMES = {
    "dark": {
        "name": "暗黑模式",
        "bg_main": "#0d1117",
        "bg_panel": "#161b22",
        "bg_header": "#1c2333",
        "bg_input": "#0d1117",
        "bg_button": "#238636",
        "bg_button_hover": "#2ea043",
        "bg_button_danger": "#da3633",
        "bg_button_danger_hover": "#f85149",
        "bg_slider_trough": "#21262d",
        "bg_slider_active": "#388bfd",
        "bg_card": "#161b22",
        "bg_card_border": "#30363d",
        "text_primary": "#e6edf3",
        "text_secondary": "#8b949e",
        "text_dim": "#6e7681",
        "text_muted": "#484f58",
        "accent_blue": "#58a6ff",
        "accent_green": "#3fb950",
        "accent_orange": "#d29922",
        "accent_red": "#f85149",
        "accent_purple": "#bc8cff",
        "accent_cyan": "#39d2c0",
        "border_color": "#30363d",
        "border_light": "#21262d",
        "shadow": "#010409",
        "console_bg": "#0d1117",
        "console_text": "#8b949e",
        "waveform_line": "#bc8cff",
        "waveform_grid": "#21262d",
        "waveform_bg": "#0d1117",
        "qr_border": "#30363d",
        "gradient_top": "#161b22",
        "gradient_bottom": "#0d1117",
    },
    "light": {
        "name": "明亮模式",
        "bg_main": "#f6f8fa",
        "bg_panel": "#ffffff",
        "bg_header": "#f3f4f6",
        "bg_input": "#f6f8fa",
        "bg_button": "#2da44e",
        "bg_button_hover": "#3fb950",
        "bg_button_danger": "#cf222e",
        "bg_button_danger_hover": "#da3633",
        "bg_slider_trough": "#d0d7de",
        "bg_slider_active": "#0969da",
        "bg_card": "#ffffff",
        "bg_card_border": "#d0d7de",
        "text_primary": "#1f2328",
        "text_secondary": "#656d76",
        "text_dim": "#8b949e",
        "text_muted": "#afb8c1",
        "accent_blue": "#0969da",
        "accent_green": "#1a7f37",
        "accent_orange": "#9a6700",
        "accent_red": "#cf222e",
        "accent_purple": "#8250df",
        "accent_cyan": "#0891b2",
        "border_color": "#d0d7de",
        "border_light": "#e8ebef",
        "shadow": "#d0d7de",
        "console_bg": "#f6f8fa",
        "console_text": "#656d76",
        "waveform_line": "#8250df",
        "waveform_grid": "#e8ebef",
        "waveform_bg": "#ffffff",
        "qr_border": "#d0d7de",
        "gradient_top": "#ffffff",
        "gradient_bottom": "#f6f8fa",
    },
}


def get_theme(name: str = "dark") -> dict:
    return THEMES.get(name, THEMES["dark"])
